# Generated by Django 4.1.1 on 2022-10-14 09:56

import accountStorage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('note', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=accountStorage.models.user_directory_path)),
                ('upload_method', models.CharField(max_length=20, verbose_name='上传方法')),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP地址')),
                ('platform', models.PositiveSmallIntegerField(choices=[(1, 'Liunx'), (2, 'Windows'), (3, 'MacOS'), (4, 'Unix'), (5, 'Other')], default=1, verbose_name='平台')),
                ('protocols', models.PositiveSmallIntegerField(choices=[(1, 'ssh'), (2, 'rdp'), (3, 'telnet'), (4, 'vnc')], default=1, verbose_name='协议')),
                ('port', models.PositiveIntegerField(verbose_name='端口')),
                ('note', models.CharField(max_length=128, verbose_name='备注')),
            ],
        ),
    ]
