# Generated by Django 4.1 on 2022-10-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountStorage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
