# Generated by Django 4.1.1 on 2022-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountStorage', '0004_adminuser_name_alter_adminuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpassword',
            name='id',
        ),
        migrations.RemoveField(
            model_name='serverinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountpassword',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='hostname',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='主机名'),
        ),
    ]
