# Generated by Django 4.1.1 on 2022-11-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountStorage', '0006_alter_serverinfo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpassword',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountpassword',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
    ]
