# Generated by Django 4.1.1 on 2022-11-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountStorage', '0007_accountpassword_id_alter_accountpassword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[('Liunx', 'Liunx'), ('Windows', 'Windows'), ('MacOS', 'MacOS'), ('Unix', 'Unix'), ('Other', 'Other')], default=1, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='protocols',
            field=models.PositiveSmallIntegerField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('telnet', 'telnet'), ('vnc', 'vnc')], default=1, verbose_name='协议'),
        ),
    ]
