# Generated by Django 4.1.1 on 2022-11-23 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountStorage', '0008_alter_serverinfo_platform_alter_serverinfo_protocols'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountStorage.accountpassword', verbose_name='密码名称'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='platform',
            field=models.PositiveSmallIntegerField(choices=[('Liunx', 'Liunx'), ('Windows', 'Windows'), ('MacOS', 'MacOS'), ('Unix', 'Unix'), ('Other', 'Other')], default='Linux', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='protocols',
            field=models.PositiveSmallIntegerField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('telnet', 'telnet'), ('vnc', 'vnc')], default='ssh', verbose_name='协议'),
        ),
    ]
