# Generated by Django 4.1.1 on 2022-11-23 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountStorage', '0010_alter_serverinfo_platform_alter_serverinfo_protocols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountStorage.accountpassword', verbose_name='密码名称'),
        ),
    ]
