# Generated by Django 4.1.1 on 2022-11-23 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountStorage', '0011_alter_serverinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='credentials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountStorage.accountpassword', verbose_name='账户凭证'),
        ),
    ]
