# Generated by Django 4.1 on 2022-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountStorage', '0013_alter_serverinfo_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='名称'),
        ),
    ]
